/**
 * Append-only extender for prebuilt level chunks.
 *
 * Generates levels BEYOND the current manifest maxLevel and writes them as new
 * chunks, WITHOUT regenerating existing chunks (preserves manually-repaired
 * levels like 93). Saves progress after each chunk so it is resumable and the
 * app can use whatever has been built so far.
 *
 * Usage: npx tsx scripts/extend-prebuilt-chunks.ts [targetMax]
 */
import fs from "fs";
import path from "path";
import type { Level } from "../src/levelModel";
import type { PrebuiltChunk, PrebuiltManifest } from "../src/prebuiltChunkTypes";
import {
  getLevelActiveCellSet,
  levelArrowsExitValid,
} from "../src/levelModel";
import { verifyLevelMoveRules } from "../src/levelSolvability";
import {
  buildLevelFresh,
  buildConstructiveLevel,
  isLevelGenTimeout,
  repairLevelDirections,
  LEVEL_CACHE_VERSION,
} from "../src/levels";

// Per-shape-bump generation budget. The random generator gives organic levels
// where it succeeds quickly; anything slower falls back to the constructive
// builder (guaranteed-solvable, multi-cell, instant), so the build is bounded
// and never produces filler. Sized to capture quick random successes only.
const PER_LEVEL_BUDGET_MS = 8_000;

const prebuiltDir = path.join(__dirname, "..", "src", "data", "prebuilt");
const manifestPath = path.join(prebuiltDir, "manifest.json");
const generatedPath = path.join(
  __dirname,
  "..",
  "src",
  "prebuiltChunks.generated.ts"
);

const targetMax = Number(process.argv[2] || 300);

const manifest = JSON.parse(
  fs.readFileSync(manifestPath, "utf8")
) as PrebuiltManifest;

const chunkSize = manifest.chunkSize;

function collectErrors(level: Level, id: number): string[] {
  const errors: string[] = [];
  if (level.id !== id) errors.push(`id mismatch (${level.id} != ${id})`);
  if (level.rows < 1 || level.cols < 1) errors.push("invalid dimensions");
  if (level.arrows.length === 0) errors.push("no arrows");
  if (getLevelActiveCellSet(level).size === 0) errors.push("empty active set");
  if (!levelArrowsExitValid(level)) errors.push("arrow into own body");
  errors.push(...verifyLevelMoveRules(level));
  return [...new Set(errors)];
}

type BuildResult = { level: Level; fallback: boolean };

function buildValidLevel(id: number): BuildResult {
  // Generation is deterministic per id, so there's no point retrying the same
  // call — give it one time-bounded shot, try a direction repair, then fall
  // back to the guaranteed builder so a pathological seed can never hang.
  try {
    const candidate = buildLevelFresh(id, { budgetMs: PER_LEVEL_BUDGET_MS });
    if (collectErrors(candidate, id).length === 0) {
      return { level: candidate, fallback: false };
    }
    const fixed = repairLevelDirections(candidate);
    if (fixed && collectErrors(fixed, id).length === 0) {
      return { level: fixed, fallback: false };
    }
  } catch (err) {
    if (!isLevelGenTimeout(err)) {
      // Non-timeout error: log and still fall back rather than aborting build.
      console.warn(
        `  level ${id}: generation error — ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  const constructive = buildConstructiveLevel(id);
  const constructiveErrors = collectErrors(constructive, id);
  if (constructiveErrors.length > 0) {
    throw new Error(
      `Constructive fallback for level ${id} failed validation: ${constructiveErrors.join("; ")}`
    );
  }
  return { level: constructive, fallback: true };
}

function chunkFileName(index: number): string {
  return `chunk-${String(index).padStart(3, "0")}.json`;
}

function chunkValid(meta: { start: number; end: number; file: string }): boolean {
  const p = path.join(prebuiltDir, meta.file);
  if (!fs.existsSync(p)) return false;
  try {
    const chunk = JSON.parse(fs.readFileSync(p, "utf8")) as PrebuiltChunk;
    if (chunk.version !== LEVEL_CACHE_VERSION) return false;
    for (let id = meta.start; id <= meta.end; id++) {
      const lvl = chunk.levels[String(id)];
      if (!lvl) return false;
    }
    return true;
  } catch {
    return false;
  }
}

function writeManifestAndLoader(m: PrebuiltManifest): void {
  fs.writeFileSync(manifestPath, JSON.stringify(m, null, 2));

  const switchCases = m.chunks
    .map(
      (c) =>
        `    case ${c.index}:\n      return require("./data/prebuilt/${c.file}") as PrebuiltChunk;`
    )
    .join("\n");

  const generated = `/** Auto-generated by scripts/extend-prebuilt-chunks.ts — do not edit. */
import type { PrebuiltChunk, PrebuiltManifest } from "./prebuiltChunkTypes";

export const PREBUILT_MANIFEST = require("./data/prebuilt/manifest.json") as PrebuiltManifest;

export function loadPrebuiltChunk(index: number): PrebuiltChunk {
  switch (index) {
${switchCases}
    default:
      throw new Error(\`Unknown prebuilt chunk index \${index}\`);
  }
}
`;
  fs.writeFileSync(generatedPath, generated);
}

if (targetMax <= manifest.maxLevel) {
  console.log(
    `Target ${targetMax} <= current maxLevel ${manifest.maxLevel}; nothing to do.`
  );
  process.exit(0);
}

const totalChunks = Math.ceil(targetMax / chunkSize);
console.log(
  `Extending prebuilt levels ${manifest.maxLevel + 1}–${targetMax} ` +
    `(chunkSize ${chunkSize}, chunks up to #${totalChunks})\n`
);

const t0 = Date.now();

for (let index = 1; index <= totalChunks; index++) {
  const start = (index - 1) * chunkSize + 1;
  const end = Math.min(targetMax, start + chunkSize - 1);
  const file = chunkFileName(index);
  const meta = { index, start, end, file };

  // Skip existing, valid chunks (preserves 1–200 and supports resume).
  if (chunkValid(meta)) {
    continue;
  }

  const chunkStart = Date.now();
  const levels: Record<string, Level> = {};
  let fallbackCount = 0;
  for (let id = start; id <= end; id++) {
    const lt0 = Date.now();
    const { level, fallback } = buildValidLevel(id);
    levels[String(id)] = level;
    if (fallback) fallbackCount++;
    const lms = Date.now() - lt0;
    const flag = fallback ? "  <-- fallback" : lms > 5000 ? "  <-- slow" : "";
    console.log(`  level ${id}: ${lms} ms${flag}`);
  }

  const chunk: PrebuiltChunk = {
    version: LEVEL_CACHE_VERSION,
    index,
    start,
    end,
    levels,
  };
  fs.writeFileSync(path.join(prebuiltDir, file), JSON.stringify(chunk));

  // Update manifest entry for this chunk.
  const existingIdx = manifest.chunks.findIndex((c) => c.index === index);
  if (existingIdx >= 0) manifest.chunks[existingIdx] = meta;
  else manifest.chunks.push(meta);
  manifest.chunks.sort((a, b) => a.index - b.index);
  manifest.maxLevel = Math.max(manifest.maxLevel, end);
  manifest.version = LEVEL_CACHE_VERSION;
  writeManifestAndLoader(manifest);

  const sizeKb = (
    fs.statSync(path.join(prebuiltDir, file)).size / 1024
  ).toFixed(1);
  const secs = ((Date.now() - chunkStart) / 1000).toFixed(1);
  const fb = fallbackCount > 0 ? `, ${fallbackCount} fallback` : "";
  console.log(
    `chunk ${index} (levels ${start}–${end}) written — ${sizeKb} KB, ${secs}s${fb}\n`
  );
}

console.log(
  `Done. maxLevel now ${manifest.maxLevel}. Total ${((Date.now() - t0) / 1000 / 60).toFixed(1)} min.`
);
