/**
 * Pre-generates levels into chunked JSON assets (20 per file) so the app loads
 * only the batch it needs instead of parsing the entire campaign at once.
 *
 * Usage: npx tsx scripts/prebuild-levels.ts [maxLevel] [chunkSize]
 */
import fs from "fs";
import path from "path";
import type { Level } from "../src/levelModel";
import type { PrebuiltChunk, PrebuiltManifest } from "../src/prebuiltChunkTypes";
import { buildLevelFresh, LEVEL_CACHE_VERSION } from "../src/levels";

const maxLevel = Number(process.argv[2] || 200);
const chunkSize = Number(process.argv[3] || 20);
const outDir = path.join(__dirname, "..", "src", "data", "prebuilt");
const generatedPath = path.join(
  __dirname,
  "..",
  "src",
  "prebuiltChunks.generated.ts"
);

const levels: Record<string, Level> = {};
const t0 = Date.now();
let slowest = { id: 0, ms: 0 };

for (let id = 1; id <= maxLevel; id++) {
  const start = Date.now();
  levels[String(id)] = buildLevelFresh(id);
  const ms = Date.now() - start;
  if (ms > slowest.ms) slowest = { id, ms };
  if (id % 25 === 0 || id === maxLevel) {
    const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
    console.log(`… generated ${id}/${maxLevel} (${elapsed}s)`);
  }
}

fs.mkdirSync(outDir, { recursive: true });

const chunkCount = Math.ceil(maxLevel / chunkSize);
const manifestChunks: PrebuiltManifest["chunks"] = [];

for (let i = 0; i < chunkCount; i++) {
  const index = i + 1;
  const start = i * chunkSize + 1;
  const end = Math.min(maxLevel, start + chunkSize - 1);
  const file = `chunk-${String(index).padStart(3, "0")}.json`;
  const chunkLevels: Record<string, Level> = {};
  for (let id = start; id <= end; id++) {
    chunkLevels[String(id)] = levels[String(id)];
  }
  const chunk: PrebuiltChunk = {
    version: LEVEL_CACHE_VERSION,
    index,
    start,
    end,
    levels: chunkLevels,
  };
  fs.writeFileSync(path.join(outDir, file), JSON.stringify(chunk));
  manifestChunks.push({ index, start, end, file });
}

const manifest: PrebuiltManifest = {
  version: LEVEL_CACHE_VERSION,
  chunkSize,
  maxLevel,
  chunks: manifestChunks,
};
fs.writeFileSync(
  path.join(outDir, "manifest.json"),
  JSON.stringify(manifest, null, 2)
);

const switchCases = manifestChunks
  .map(
    (c) =>
      `    case ${c.index}:\n      return require("./data/prebuilt/${c.file}") as PrebuiltChunk;`
  )
  .join("\n");

fs.writeFileSync(
  generatedPath,
  `/** Auto-generated by scripts/prebuild-levels.ts — do not edit. */
import type { PrebuiltChunk, PrebuiltManifest } from "./prebuiltChunkTypes";

export const PREBUILT_MANIFEST = require("./data/prebuilt/manifest.json") as PrebuiltManifest;

export function loadPrebuiltChunk(index: number): PrebuiltChunk {
  switch (index) {
${switchCases}
    default:
      throw new Error(\`Unknown prebuilt chunk index \${index}\`);
  }
}
`
);

const totalKb =
  manifestChunks.reduce(
    (sum, c) => sum + fs.statSync(path.join(outDir, c.file)).size,
    0
  ) / 1024;

console.log(
  `\nWrote ${chunkCount} chunks × ${chunkSize} levels (v${LEVEL_CACHE_VERSION}, ${totalKb.toFixed(0)} KB) to ${outDir}`
);
console.log(
  `Total ${((Date.now() - t0) / 1000).toFixed(1)}s, slowest level ${slowest.id} at ${slowest.ms}ms`
);
