/**
 * Split monolithic prebuiltLevels.json into 20-level chunks + manifest.
 * Also regenerates src/prebuiltChunks.generated.ts with static require() loaders.
 *
 * Usage: npx tsx scripts/split-prebuilt-chunks.ts [chunkSize] [sourceJson]
 */
import fs from "fs";
import path from "path";
import type { Level } from "../src/levelModel";
import type { PrebuiltChunk, PrebuiltManifest } from "../src/prebuiltChunkTypes";

const chunkSize = Number(process.argv[2] || 20);
const sourcePath =
  process.argv[3] ||
  path.join(__dirname, "..", "src", "data", "prebuiltLevels.json");
const outDir = path.join(__dirname, "..", "src", "data", "prebuilt");
const generatedPath = path.join(
  __dirname,
  "..",
  "src",
  "prebuiltChunks.generated.ts"
);

type Monolithic = {
  version: number;
  maxLevel: number;
  levels: Record<string, Level>;
};

const raw = JSON.parse(fs.readFileSync(sourcePath, "utf8")) as Monolithic;
const cacheVersion = raw.version;
const maxLevel = raw.maxLevel;
const chunkCount = Math.ceil(maxLevel / chunkSize);

fs.mkdirSync(outDir, { recursive: true });

const manifestChunks: PrebuiltManifest["chunks"] = [];

for (let i = 0; i < chunkCount; i++) {
  const index = i + 1;
  const start = i * chunkSize + 1;
  const end = Math.min(maxLevel, start + chunkSize - 1);
  const file = `chunk-${String(index).padStart(3, "0")}.json`;
  const levels: Record<string, Level> = {};

  for (let id = start; id <= end; id++) {
    const level = raw.levels[String(id)];
    if (level) levels[String(id)] = level;
  }

  const chunk: PrebuiltChunk = {
    version: cacheVersion,
    index,
    start,
    end,
    levels,
  };

  const outPath = path.join(outDir, file);
  fs.writeFileSync(outPath, JSON.stringify(chunk));
  const sizeKb = (fs.statSync(outPath).size / 1024).toFixed(1);
  manifestChunks.push({ index, start, end, file });
  console.log(`  chunk ${index}: levels ${start}–${end} → ${file} (${sizeKb} KB)`);
}

const manifest: PrebuiltManifest = {
  version: cacheVersion,
  chunkSize,
  maxLevel,
  chunks: manifestChunks,
};

fs.writeFileSync(
  path.join(outDir, "manifest.json"),
  JSON.stringify(manifest, null, 2)
);

const switchCases = manifestChunks
  .map(
    (c) =>
      `    case ${c.index}:\n      return require("./data/prebuilt/${c.file}") as PrebuiltChunk;`
  )
  .join("\n");

const generatedTs = `/** Auto-generated by scripts/split-prebuilt-chunks.ts — do not edit. */
import type { PrebuiltChunk, PrebuiltManifest } from "./prebuiltChunkTypes";

export const PREBUILT_MANIFEST = require("./data/prebuilt/manifest.json") as PrebuiltManifest;

export function loadPrebuiltChunk(index: number): PrebuiltChunk {
  switch (index) {
${switchCases}
    default:
      throw new Error(\`Unknown prebuilt chunk index \${index}\`);
  }
}
`;

fs.writeFileSync(generatedPath, generatedTs);

const totalKb = manifestChunks
  .reduce((sum, c) => sum + fs.statSync(path.join(outDir, c.file)).size, 0) / 1024;

console.log(
  `\nWrote ${chunkCount} chunks (v${cacheVersion}, ${chunkSize}/batch, ${totalKb.toFixed(0)} KB total)`
);
console.log(`Manifest: src/data/prebuilt/manifest.json`);
console.log(`Loaders:  src/prebuiltChunks.generated.ts`);
