/** Auto-generated by scripts/extend-prebuilt-chunks.ts — do not edit. */
import type { PrebuiltChunk, PrebuiltManifest } from "./prebuiltChunkTypes";

export const PREBUILT_MANIFEST = require("./data/prebuilt/manifest.json") as PrebuiltManifest;

export function loadPrebuiltChunk(index: number): PrebuiltChunk {
  switch (index) {
    case 1:
      return require("./data/prebuilt/chunk-001.json") as PrebuiltChunk;
    case 2:
      return require("./data/prebuilt/chunk-002.json") as PrebuiltChunk;
    case 3:
      return require("./data/prebuilt/chunk-003.json") as PrebuiltChunk;
    case 4:
      return require("./data/prebuilt/chunk-004.json") as PrebuiltChunk;
    case 5:
      return require("./data/prebuilt/chunk-005.json") as PrebuiltChunk;
    case 6:
      return require("./data/prebuilt/chunk-006.json") as PrebuiltChunk;
    case 7:
      return require("./data/prebuilt/chunk-007.json") as PrebuiltChunk;
    case 8:
      return require("./data/prebuilt/chunk-008.json") as PrebuiltChunk;
    case 9:
      return require("./data/prebuilt/chunk-009.json") as PrebuiltChunk;
    case 10:
      return require("./data/prebuilt/chunk-010.json") as PrebuiltChunk;
    default:
      throw new Error(`Unknown prebuilt chunk index ${index}`);
  }
}
