/** Auto-generated by scripts/extend-prebuilt-chunks.ts — do not edit. */
import type { PrebuiltChunk, PrebuiltManifest } from "./prebuiltChunkTypes";

export const PREBUILT_MANIFEST = require("./data/prebuilt/manifest.json") as PrebuiltManifest;

export function loadPrebuiltChunk(index: number): PrebuiltChunk {
  switch (index) {
    case 1:
      return require("./data/prebuilt/chunk-001.json") as PrebuiltChunk;
    case 2:
      return require("./data/prebuilt/chunk-002.json") as PrebuiltChunk;
    case 3:
      return require("./data/prebuilt/chunk-003.json") as PrebuiltChunk;
    case 4:
      return require("./data/prebuilt/chunk-004.json") as PrebuiltChunk;
    case 5:
      return require("./data/prebuilt/chunk-005.json") as PrebuiltChunk;
    case 6:
      return require("./data/prebuilt/chunk-006.json") as PrebuiltChunk;
    case 7:
      return require("./data/prebuilt/chunk-007.json") as PrebuiltChunk;
    case 8:
      return require("./data/prebuilt/chunk-008.json") as PrebuiltChunk;
    case 9:
      return require("./data/prebuilt/chunk-009.json") as PrebuiltChunk;
    case 10:
      return require("./data/prebuilt/chunk-010.json") as PrebuiltChunk;
    case 11:
      return require("./data/prebuilt/chunk-011.json") as PrebuiltChunk;
    case 12:
      return require("./data/prebuilt/chunk-012.json") as PrebuiltChunk;
    case 13:
      return require("./data/prebuilt/chunk-013.json") as PrebuiltChunk;
    case 14:
      return require("./data/prebuilt/chunk-014.json") as PrebuiltChunk;
    case 15:
      return require("./data/prebuilt/chunk-015.json") as PrebuiltChunk;
    case 16:
      return require("./data/prebuilt/chunk-016.json") as PrebuiltChunk;
    case 17:
      return require("./data/prebuilt/chunk-017.json") as PrebuiltChunk;
    case 18:
      return require("./data/prebuilt/chunk-018.json") as PrebuiltChunk;
    case 19:
      return require("./data/prebuilt/chunk-019.json") as PrebuiltChunk;
    case 20:
      return require("./data/prebuilt/chunk-020.json") as PrebuiltChunk;
    case 21:
      return require("./data/prebuilt/chunk-021.json") as PrebuiltChunk;
    case 22:
      return require("./data/prebuilt/chunk-022.json") as PrebuiltChunk;
    case 23:
      return require("./data/prebuilt/chunk-023.json") as PrebuiltChunk;
    case 24:
      return require("./data/prebuilt/chunk-024.json") as PrebuiltChunk;
    case 25:
      return require("./data/prebuilt/chunk-025.json") as PrebuiltChunk;
    case 26:
      return require("./data/prebuilt/chunk-026.json") as PrebuiltChunk;
    case 27:
      return require("./data/prebuilt/chunk-027.json") as PrebuiltChunk;
    case 28:
      return require("./data/prebuilt/chunk-028.json") as PrebuiltChunk;
    case 29:
      return require("./data/prebuilt/chunk-029.json") as PrebuiltChunk;
    case 30:
      return require("./data/prebuilt/chunk-030.json") as PrebuiltChunk;
    default:
      throw new Error(`Unknown prebuilt chunk index ${index}`);
  }
}
